### ISSUE TITLE
twitch helix api?

### ISSUE THREAD

**Issue by dinosaw** [mwalbeck/twitchlite#8]
hello! any plans to convert this over to the new helix api, as they are decommissioning api v5 early next year. i tried a few things myself like changing the kraken to helix, and the oauth token header to "Authorization: Bearer xxxx" in the logic file, and using a "new" client id since newly created client ids don't have access to kraken. but i keep getting an error about line 44 on the index.php file. this would be greatly appreciated!

**Comment by mwalbeck** [comment]
Hi, I've actually tried a couple of times to update but every time I ended up dropping it as the helix api didn't have the endpoint simple endpoints needed to actually make it work properly. So I thought I would have to bring some bad news. But after all this time it seems like they finally implemented the basic endpoints needed! I thought the day would never come.

So thanks for bringing it to my attention, I most likely would have missed the deadline otherwise. I'll have a look when I have some spare time and get it updated.

Cheers!

**Comment by mwalbeck** [comment]
Hi, there should now be a functional version of twitchlite that uses the Helix api. I haven't quite merged it into master yet, but it's available in the Helix branch. It would be great if you could get a spin.

There are two noticeable difference between the two versions: 

First, pagination seems to be kind of a mess if you want to go back to previous pages, so I have removed that option. Instead, I have added a button to go back to the beginning.

Second, games now use a numerical ID instead of their names. So I've decided to enable retrieve top games by default and set the amount to 100 (the max). The autocomplete list displays the names of the games when typing, but when you select it the ID is shown. You can still input arbitrary values into the field, but you would have to find the ID of the game. Currently, I don't have a good tip for quickly finding them.

The setup instructions can be found in the README in the helix branch.

Cheers!
